# action.yml
name: 'Docker Run Action'
description: 'Run a command in a new container'
inputs:
  image:
    description: 'Image'
    required: true
  options:
    description: 'Options'
    required: false
  run:
    description: 'Run command in container'
    required: false
  shell:
    description: 'Use a specific shell'
    required: false
    default: sh
  registry:
    description: 'Registry'
    required: false
  username:
    description: 'Username'
    required: false
  password:
    description: 'Password'
    required: false
  docker_network:
    description: 'Docker Network ID'
    default: ${{ job.container.network }}
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/step-security/docker-run-action:v3.0.0@sha256:f152d8b6f0c410597195fbada66293b1ab36e5156cc8f8757cf5b4e0dc63248a' #v3.0.0
